[package]
name = "gpu"
version = "0.1.4"
authors = ["Danilo Guanabara <danguafer@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An ergonomic GPU API"
documentation = "https://docs.rs/gpu/0.1.0/gpu/"
readme = "README.md"
repository = "https://github.com/danguafer/gpu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.20.0"
gl = "0.11.0"
