[package]
name = "gpu"
version = "0.1.0"
authors = ["Danilo Guanabara <danguafer@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An ergonomic GPU API"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.20.0"
gl = "0.11.0"
